const $=(s)=>document.querySelector(s);const $$=(s)=>Array.from(document.querySelectorAll(s));
const SUBJECTS=window.SUBJECTS||[];const GUIDES=window.SUMMARY_GUIDES||[];const BASE=window.SAMPLE_QUESTIONS||[];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=(v)=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const pct=(a,b)=>b?Math.round(a/b*100):0;const shuffle=(a)=>[...a].sort(()=>Math.random()-.5);const today=()=>new Date().toISOString().slice(0,10);
let stats=read('sw1_stats',{date:today(),solved:0,correct:0,streak:0,subject:{}});let wrong=read('sw1_wrong',[]);let learned=read('sw1_learned',[]);let custom=read('sw1_custom',[]);let current=[];let timer=null;let left=1500;
function questions(){return BASE.concat(custom)}
function save(){write('sw1_stats',stats);write('sw1_wrong',wrong);write('sw1_learned',learned);write('sw1_custom',custom)}
function dayCheck(){if(stats.date!==today()){let y=new Date(Date.now()-86400000).toISOString().slice(0,10);stats.streak=stats.date===y?(stats.streak||0)+1:1;stats.date=today();stats.solved=0;stats.correct=0;save()}}
function view(v){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.toggle('active',x.id===v+'View'));$('#viewTitle').textContent=$('#'+v+'View')?.dataset.title||'학습 홈';if(v==='summary')summary();if(v==='wrong')wrongView();if(v==='library')library()}
function dashboard(){dayCheck();let r=pct(stats.correct,stats.solved);$('#statSolved').textContent=stats.solved;$('#statCorrect').textContent=r+'%';$('#statWrong').textContent=(stats.streak||0)+'일';$('#statSavedWrong').textContent=wrong.length;$('#meterRate').textContent=r+'%';$('#meterFill').style.width=r+'%';let goal=Number($('#dailyGoalInput')?.value||20);$('#dailyPlanText').textContent=`${stats.solved}/${goal}문항 완료`;$('#goalFill').style.width=Math.min(100,pct(stats.solved,goal))+'%';dday();let box=$('#dashboardSubjects');if(!box)return;box.innerHTML=SUBJECTS.map(s=>{let st=stats.subject[s]||{solved:0,correct:0};let n=questions().filter(q=>q.subject===s).length;return `<button class="subject-button" data-s="${esc(s)}"><strong>${esc(s)}</strong><span>${n}문항 · 정확도 ${pct(st.correct,st.solved)}%</span></button>`}).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{view('quiz');$('#quizSubject').value=b.dataset.s;startQuiz(b.dataset.s,10)})}
function dday(){let input=$('#examDateInput'),badge=$('#examDday');if(!input||!badge)return;let saved=read('sw1_exam','');if(saved&&!input.value)input.value=saved;if(!input.value){badge.textContent='시험일 미설정';return}let d=Math.ceil((new Date(input.value)-new Date(today()))/86400000);badge.textContent=d>=0?'D-'+d:'D+'+Math.abs(d)}
function initSelects(){['#summarySubject','#quizSubject'].forEach(id=>{let e=$(id);if(e)e.innerHTML='<option value="">전체</option>'+SUBJECTS.map(s=>`<option>${esc(s)}</option>`).join('')});let tags=[...new Set(GUIDES.flatMap(g=>g.tags||[]))];let t=$('#summaryTag');if(t)t.innerHTML='<option value="">전체</option>'+tags.map(x=>`<option>${esc(x)}</option>`).join('')}
function summary(){let sub=$('#summarySubject')?.value||'',tag=$('#summaryTag')?.value||'',kw=($('#summarySearch')?.value||'').toLowerCase().trim(),exam=$('#examModeToggle')?.checked;let cards=GUIDES.filter(g=>{let text=[g.subject,g.unit,g.title,g.oneLine,g.examPoint,g.trap,g.memoryLine,...(g.tags||[])].join(' ').toLowerCase();return(!sub||g.subject===sub)&&(!tag||g.tags?.includes(tag))&&(!kw||text.includes(kw))});$('#summaryCount').textContent=`${cards.length}개 개념 정리 · ${exam?'시험 직전 압축 모드':'상세 학습 모드'}`;$('#summaryList').innerHTML=cards.length?cards.map(g=>card(g,exam)).join(''):'<div class="panel empty-state">검색 결과가 없습니다.</div>';$('#summaryList').querySelectorAll('[data-learn]').forEach(b=>b.onclick=()=>{learned=learned.includes(b.dataset.learn)?learned.filter(x=>x!==b.dataset.learn):learned.concat(b.dataset.learn);save();summary()});$('#summaryList').querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{view('quiz');startQuiz(b.dataset.q,5)});flash(cards)}
function card(g,exam){let ok=learned.includes(g.id);let tags=(g.tags||[]).map(t=>`<span class="tag ${t==='법령'?'warn':t==='실천연결'?'good':''}">${esc(t)}</span>`).join('');let detail=exam?'':`<div class="summary-grid"><div class="summary-box"><strong>핵심 내용</strong><ul>${g.corePoints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="summary-box"><strong>비교 개념</strong><ul>${(g.compare||[]).map(c=>`<li><b>${esc(c.title)}</b>: ${esc(c.description)}</li>`).join('')}</ul></div><div class="summary-box"><strong>기출 포인트</strong><p>${esc(g.examPoint)}</p></div><div class="summary-box"><strong>오답 함정</strong><p>${esc(g.trap)}</p></div></div>`;return `<article class="summary-card ${ok?'learned':''}"><div class="summary-head"><div><p class="eyebrow">${esc(g.subject)} · ${esc(g.unit)}</p><h3 class="summary-title">${esc(g.title)}</h3></div><div class="tag-row">${tags}</div></div><p class="summary-one">${esc(g.oneLine)}</p><div class="summary-box"><strong>암기 문장</strong><p>${esc(g.memoryLine)}</p></div>${detail}<div class="summary-foot"><button class="small-button" data-learn="${g.id}">${ok?'암기 취소':'암기 완료'}</button><button class="small-button" data-q="${esc(g.subject)}">관련 문제 풀기</button></div></article>`}
function flash(cards){let box=$('#flashList');if(!box)return;let done=cards.filter(c=>learned.includes(c.id)).length;box.innerHTML=`<div class="flash-item"><strong>${done}/${cards.length}</strong><span>현재 목록 암기 완료</span></div>`+cards.filter(c=>!learned.includes(c.id)).slice(0,8).map(c=>`<div class="flash-item"><strong>${esc(c.title)}</strong><span>${esc(c.memoryLine)}</span></div>`).join('')}
function startQuiz(subject='',count=10,mode='quiz'){let pool=questions().filter(q=>!subject||q.subject===subject);current=shuffle(pool.length?pool:questions()).slice(0,Math.max(1,count));renderQ(mode==='cbt'?'#cbtArea':'#quizArea');if(mode!=='cbt')view('quiz')}
function renderQ(target){let box=$(target);if(!box)return;box.classList.remove('empty-state');box.innerHTML=current.map((q,i)=>`<article class="question-card" data-id="${esc(q.id)}"><div class="question-meta">${i+1}. ${esc(q.subject)} · ${(q.tags||[]).join(' · ')}</div><h4>${esc(q.question)}</h4><div>${q.choices.map((c,n)=>`<label class="choice"><input type="radio" name="${esc(q.id)}" value="${n}"><span>${n+1}. ${esc(c)}</span></label>`).join('')}</div><div class="explain">${esc(q.explain)}</div></article>`).join('');updateSheet()}
function grade(mode='quiz'){let target=mode==='cbt'?'#cbtArea':'#quizArea';let cards=$$(target+' .question-card');if(!cards.length)return;let good=0;cards.forEach(c=>{let q=current.find(x=>x.id===c.dataset.id);if(!q)return;let v=Number(c.querySelector('input:checked')?.value??-1),ok=v===q.answer;if(ok)good++;c.classList.add('graded');c.querySelectorAll('.choice').forEach((ch,i)=>{ch.classList.toggle('correct-choice',i===q.answer);ch.classList.toggle('wrong-choice',i===v&&!ok)});if(ok)wrong=wrong.filter(w=>w.id!==q.id);else{let e=wrong.find(w=>w.id===q.id);e?e.count=(e.count||1)+1:wrong.push({...q,count:1,last:today()})}stats.subject[q.subject]=stats.subject[q.subject]||{solved:0,correct:0};stats.subject[q.subject].solved++;if(ok)stats.subject[q.subject].correct++});stats.solved+=cards.length;stats.correct+=good;save();if(mode!=='cbt'){ $('#quizScore').textContent=`${good} / ${cards.length}`;$('#quizPercent').textContent='정확도 '+pct(good,cards.length)+'%'}dashboard();if(mode==='cbt')stop()}
function startCbt(){view('cbt');startQuiz('',25,'cbt');left=1500;stop();tick();timer=setInterval(()=>{left--;tick();if(left<=0){stop();grade('cbt')}},1000)}function stop(){if(timer)clearInterval(timer);timer=null}function tick(){let m=Math.floor(left/60),s=left%60;$('#timer').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function updateSheet(){let s=$('#answerSheet');if(!s)return;s.innerHTML=current.map((q,i)=>`<button class="answer-chip">${i+1}</button>`).join('')}
function wrongView(){let list=$('#wrongList');if(!wrong.length){list.innerHTML='<div class="empty-state">아직 오답이 없습니다.</div>';$('#wrongRelated').innerHTML='';return}list.innerHTML=wrong.map(q=>`<div class="wrong-item"><strong>${esc(q.question)}</strong><p class="muted">${esc(q.subject)} · ${q.count||1}회 오답</p><p>${esc(q.explain)}</p></div>`).join('');let subs=[...new Set(wrong.map(q=>q.subject))];let rel=GUIDES.filter(g=>subs.includes(g.subject)).slice(0,6);$('#wrongRelated').innerHTML='<h3>관련 요약</h3><div class="summary-list">'+rel.map(g=>card(g,true)).join('')+'</div>'}
function retryWrong(){if(!wrong.length){alert('복습할 오답이 없습니다.');return}current=shuffle(wrong).slice(0,10);renderQ('#quizArea');view('quiz')}
function library(){let box=$('#libraryStats');if(!box)return;box.innerHTML='<div class="stats-grid">'+SUBJECTS.map(s=>`<div class="stat"><span>${esc(s)}</span><strong>${questions().filter(q=>q.subject===s).length}</strong></div>`).join('')+'</div><p class="muted">기본 샘플 '+BASE.length+'문항 · 직접 추가 '+custom.length+'문항</p>'}
function importQ(){try{let arr=JSON.parse($('#importBox').value);if(!Array.isArray(arr))throw Error('JSON 배열이 아닙니다.');let add=arr.filter(q=>q.question&&Array.isArray(q.choices)).map((q,i)=>({id:q.id||'custom-'+Date.now()+'-'+i,subject:q.subject||SUBJECTS[0],tags:q.tags||['직접추가'],question:q.question,choices:q.choices,answer:Number(q.answer||0),explain:q.explain||'직접 추가한 문제입니다.'}));custom=custom.concat(add);save();alert(add.length+'문항을 추가했습니다.');library();dashboard()}catch(e){alert('가져오기 실패: '+e.message)}}
function boot(){dayCheck();initSelects();$$('.nav-item').forEach(b=>b.onclick=()=>view(b.dataset.view));['#summarySubject','#summaryTag','#summarySearch','#examModeToggle'].forEach(id=>$(id)?.addEventListener('input',summary));$('#examDateInput')?.addEventListener('change',e=>{write('sw1_exam',e.target.value);dashboard()});$('#dailyGoalInput')?.addEventListener('input',dashboard);$('#startQuickBtn')?.addEventListener('click',()=>startQuiz('',10));$('#startDailyBtn')?.addEventListener('click',()=>startQuiz('',Number($('#dailyGoalInput').value||20)));$('#startWeakBtn')?.addEventListener('click',()=>startQuiz(SUBJECTS[0],10));$('#buildQuizBtn')?.addEventListener('click',()=>startQuiz($('#quizSubject').value,Number($('#quizCount').value||10)));$('#finishQuizBtn')?.addEventListener('click',()=>grade('quiz'));$('#startCbtBtn')?.addEventListener('click',startCbt);$('#submitCbtBtn')?.addEventListener('click',()=>grade('cbt'));$('#reviewWrongBtn')?.addEventListener('click',()=>view('wrong'));$('#retryWrongBtn')?.addEventListener('click',retryWrong);$('#clearWrongBtn')?.addEventListener('click',()=>{wrong=[];save();wrongView();dashboard()});$('#sampleBtn')?.addEventListener('click',()=>$('#importBox').value=JSON.stringify(BASE.slice(0,2),null,2));$('#importBtn')?.addEventListener('click',importQ);$('#exportBtn')?.addEventListener('click',()=>$('#exportBox').textContent=JSON.stringify(questions(),null,2));$('#resetSessionBtn')?.addEventListener('click',()=>{stats.solved=0;stats.correct=0;save();dashboard()});dashboard();summary();library()}
document.addEventListener('DOMContentLoaded',boot);
